```mermaid
sequenceDiagram
participant F as Front
participant I as Nuvemshop IdP
participant A as Nuvemshop API
participant P as Payment App
F ->>+ I: GET apps/{appId}/authorize(credentials)
Note over I: Merchant will be<br/>prompted to log in if<br/>necessary.
I ->> I: validate(credentials)
I -->>- F: 301: {redirect_uri}(code, success_url, failure_url, cancel_url)
F ->>+ P: POST {redirect_uri}(code, success_url, failure_url, cancel_url)
Note over P: App login flow and<br/>credentials validation<br/>should be handled<br/>at this point.
P ->>+ I: POST /apps/authorize/token(code, client_id, client_secret, grant_type)
I -->>- P: 200: (access_token, token_type, scopes, user_id)
Note over P: For future usage:
P ->> P: persist(access_token, user_id)
Note over P: Payment Provider<br>creation:
P ->>+ A: POST {store_id}/payment_providers(access_token, params)
A ->>- P: 201: Created (Payment Provider)
P -->>- F: 301: {success_url}
```